### ISSUE TITLE
Docker install does not work properly

### ISSUE THREAD

**Issue by tomsej** [lyft/amundsenfrontendlibrary#64] opened 2019-04-03 15:16 UTC
### Amundsen Version
Master

### Expected results
When I follow [Installation tutorial](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/installation.md) everything works.

### Actual results
It fails with following error:
```
2019-04-03T15:43:02+0200.069 [ERROR] app.log_exception:1761 (40925:Thread-1) - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/amundsen_frontend-1.0.0-py3.6.egg/amundsen_application/api/__init__.py", line 16, in index
    return render_template("index.html")  # pragma: no cover
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/tomsejr/Documents/03-Workspace/LMC/amundsenfrontendlibrary/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```
It is same as problem mentioned at issue #6

### How to fix that
Posibilities:

- Running `npm run build` before `docker build -f public.Dockerfile -t amundsen-frontend:latest .` so `index.html` is created and copied into Docker imege during build proccess.
- Add `npm` into `amundsen-frontend` image and build everything here:
```
FROM python:3
WORKDIR /app
COPY . /app
RUN pip3 install -r requirements3.txt
RUN apt-get update \
    && apt-get -y install curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_11.x  | bash - \
    && apt-get -y install nodejs \
    && cd amundsen_application/static \
    && npm install \
    && npm run build
RUN python3 setup.py install

ENTRYPOINT [ "python3" ]
CMD [ "amundsen_application/wsgi.py" ]
```

**Comment by tomsej** [comment] 2019-04-03 15:16
BTW thank you for this wonderful project!

**Comment by feng-tao** [comment] 2019-04-03 16:40
cc @ttannis @danwom 
@tomsej , thanks for reporting the issue. Feel free to create a pr to fix the issue :)

**Comment by tomsej** [comment] 2019-04-03 18:31
@feng-tao ok will send PR tomorrow. I was not sure which way is preferable, think changing installation guide is ok for now.

**Comment by danwom** [comment] 2019-04-12 21:38
I believe this has the same root cause as https://github.com/lyft/amundsenfrontendlibrary/issues/6, and may share the same solution. Can you try following the updated instructions here https://github.com/lyft/amundsenfrontendlibrary/pull/77?

Thanks!

**Comment by feng-tao** [comment] 2019-04-16 19:19
close this issue for now, @tomsej let us know if you still encounter the same issue and feel free to reopen one.

**Closed by feng-tao** 2019-04-16 19:19 UTC
